### ISSUE TITLE
Get population by state for Germany/Poland

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid.german.forecasts#35]
In EpiNow2 forecasts can be improved if populations are known. The new state level forecasts require state level population data.

**Comment by seabbs** [comment]
@nikosbosse this might be the cause of some of the uncertainty issues you noted in the state level forecasts

**Comment by nikosbosse** [comment]
Baden-Württemberg State, 11100394
Free State of Bavaria, 3124737
Berlin State, 3669491
Brandenburg State, 2521893
Free Hanseatic City of Bremen, 681202
Free Hanseatic City of Hamburg, 1847253
Hesse State, 6288080
Mecklenburg-Western Pomerania State, 1608138
Lower Saxony State, 7993608
North Rhine-Westphalia State, 17947221
Rhineland-Palatinate State, 4093903
Saarland State, 986887
Free State of Saxony, 4071971
Sachsen-Anhalt State, 2194782
Schleswig-Holstein State, 2903773
Free State of Thüringia, 2133378
Germany, 83166711

**Comment by nikosbosse** [comment]
oh - noticed that is just Germany :-D Here is where my competitive advantage ends...

**Comment by seabbs** [comment]
Done for all geographies.
